<?php
/** @var \Application\Entity\Country $country */
/** @var \Application\Entity\City[] $cities */
?>

<p><a href="<?= $this->url('home'); ?>"><< Countries</a></p>


<h1><?= $country->getName(); ?></h1>
<h3><?= $country->getContinent(); ?></h3>

<div class="row">
    <div class="col-lg-4">
        <h5>Population:</h5>

        <p><?= $country->getPopulation(); ?></p>
    </div>

    <div class="col-lg-4">
        <h5>Surface Area</h5>

        <p><?= $country->getSurfaceArea(); ?></p>
    </div>

    <div class="col-lg-4">
        <h5>Life Expectancy</h5>

        <p><?= $country->getLifeExpectancy(); ?></p>
    </div>
</div>

<h4>Cities</h4>

<ul>
    <?php foreach ($cities as $city): ?>
        <li>
            <a href="<?= $this->url('city', ['id' => $city->getID()]); ?>">
                <?= $city->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>