<p><a href="<?= $this->url('home'); ?>"><< Countries</a></p>


<h1><?= $country['Name']; ?></h1>
<h3><?= $country['Continent']; ?></h3>

<div class="row">
    <div class="col-lg-4">
        <h5>Population:</h5>

        <p><?= $country['Population']; ?></p>
    </div>

    <div class="col-lg-4">
        <h5>Surface Area</h5>

        <p><?= $country['SurfaceArea']; ?></p>
    </div>

    <div class="col-lg-4">
        <h5>Life Expectancy</h5>

        <p><?= $country['LifeExpectancy']; ?></p>
    </div>
</div>

<h4>Cities</h4>

<ul>
    <?php foreach ($cities as $city): ?>
        <li>
            <a href="<?= $this->url('city', ['id' => $city['ID']]); ?>">
                <?= $city['Name'] ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>